---
- name: Install Filebeat
  package:
    name: "{{ filebeat_version }}"
    state: present

- name: Configure filebeat.yml file
  template:
    src: templates/filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: Start Filebeat service
  systemd:
    name: filebeat
    state: started
    enabled: yes