---
- include: master.yml
  when: inventory_hostname in groups[item]
  with_items: "{{ master_hostname}}"

- include: worker.yml
  when: inventory_hostname in groups[item]
  with_items: "{{ worker_hostname}}"