---
- name: Install NFS server
  package:
    name:
    - nfs-utils
    - nfs4-acl-tools
    state: present
    update_cache: true
  tags:
    - nfs-all
    - nfs-client

- name: Create share directory
  file:
    state: directory
    path: "{{ share_path }}"
    owner: "elasticsearch"
    group: "elasticsearch"
  tags:
    - nfs-all
    - nfs-client

- name: Mount remote repo
  remote_user: elasticsearch
  mount:
    src: "{{ nfs_server }}:{{ share_path }}"
    path: "{{ share_path }}"
    opts: rw,_netdev,tcp
    fstype: nfs
    state: mounted
  tags:
    - nfs-all
    - nfs-client

- name: Configure elasticsearch.yml repo path
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'path.repo: ["{{ share_path }}"]'
    insertafter: EOF
  tags:
    - nfs-all
    - nfs-client

- name: Restart Elasticsearch service
  systemd:
    name: elasticsearch
    state: restarted
  tags:
    - nfs-all
    - nfs-client