---
# ELK version install
elastic_version: elasticsearch
kibana_version: kibana
metricbeat_version: metricbeat
filebeat_version: filebeat
# ELK variables for all nodes
elastic_cluster_name: elk-cluster
elastic_nodes: '"10.0.2.4", "10.0.2.5", "10.0.2.6"'
kibana_host: 10.0.2.4
kibana_elastic_hosts: '"http://10.0.2.4:9200", "http://10.0.2.5:9200", "http://10.0.2.6:9200"'
# ELK variables for master/data nodes
logs_elastic_nodes: '"10.0.2.5:9200", "10.0.2.6:9200"'
# Kibana pass variable
kibana_pass: '"8qMyBgf4VCDSZyjN6NAVJZs2UPyQGnGZ"'
# ELK role variables
group_hostname: ['elk_cluster']
master_hostname: ['elk_master']
worker_hostname: ['elk_worker']
# NFS share role variables
nfs_server: 10.0.2.4
nfs_client_1: 10.0.2.5
nfs_client_2: 10.0.2.6
share_path: /mnt/elasticshare
